[build]
  functions = "functions"
  command = "#"
[template.environment]
  GOOGLE_SERVICE_ACCOUNT_EMAIL = "Google Service Account Email"
  GOOGLE_SPREADSHEET_ID_FROM_URL = "Google Spreadsheet ID"
  GOOGLE_PRIVATE_KEY = "Goggle Account Private Key"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
